version: "3.8"

services:
  app:
    container_name: kiken-app
    image: kiken-app
    build:
      context: .
    volumes:
      - ./app:/app:delegated
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true